# Generated by Django 2.2 on 2021-09-19 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp2', '0002_breakfastgenre_breakfastingredient_dinnergenre_dinneringredient_lunchgenre_lunchingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfastgenre',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bgenres', to='groceryapp2.User'),
        ),
    ]
