# Generated by Django 2.2 on 2021-09-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp2', '0003_auto_20210919_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='BLD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.CharField(max_length=50)),
                ('lunch', models.CharField(max_length=50)),
                ('dinner', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genre', models.ManyToManyField(to='groceryapp2.Genre')),
            ],
        ),
        migrations.RemoveField(
            model_name='breakfastingredient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dinnergenre',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dinneringredient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lunchgenre',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lunchingredient',
            name='user',
        ),
        migrations.DeleteModel(
            name='BreakfastGenre',
        ),
        migrations.DeleteModel(
            name='BreakfastIngredient',
        ),
        migrations.DeleteModel(
            name='DinnerGenre',
        ),
        migrations.DeleteModel(
            name='DinnerIngredient',
        ),
        migrations.DeleteModel(
            name='LunchGenre',
        ),
        migrations.DeleteModel(
            name='LunchIngredient',
        ),
        migrations.AddField(
            model_name='bld',
            name='genre',
            field=models.ManyToManyField(to='groceryapp2.Genre'),
        ),
        migrations.AddField(
            model_name='bld',
            name='ingredient',
            field=models.ManyToManyField(to='groceryapp2.Ingredient'),
        ),
    ]
