# Generated by Django 2.2 on 2021-09-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp2', '0004_auto_20210919_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bld',
            name='genre',
            field=models.ManyToManyField(related_name='BLDGenre', to='groceryapp2.Genre'),
        ),
        migrations.AlterField(
            model_name='bld',
            name='ingredient',
            field=models.ManyToManyField(related_name='BLDIngredient', to='groceryapp2.Ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='genre',
            field=models.ManyToManyField(related_name='ingredientgenre', to='groceryapp2.Genre'),
        ),
    ]
