# Generated by Django 2.2 on 2021-09-20 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp2', '0005_auto_20210920_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='named',
        ),
    ]
