# Generated by Django 2.2 on 2021-09-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp2', '0006_auto_20210920_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='menu',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.DeleteModel(
            name='BLD',
        ),
    ]
